core/booking/barbers/urls.py
from django.urls import path
from .views import BarberPanelView, BarberScheduleView

app_name = "barbers"
urlpatterns = [
    path("<int:barber_id>", BarberPanelView.as_view(), name="barber_panel"),
    path(
        "<int:barber_id>/barber-schedule/",
        BarberScheduleView.as_view(),
        name="barber_schedule",
    ),
]

core/booking/urls.py
from django.urls import path

from .views import (
    BookingDateView,
    BookingTimeView,
    BookingSuccessView,
    BookingProccessView,
)

app_name = "booking"

urlpatterns = [
    path("<int:barber_id>/", BookingDateView.as_view(), name="booking_date"),
    path("<int:barber_id>/time/", BookingTimeView.as_view(), name="booking_time"),
    path("booking_proccessing", BookingProccessView.as_view(), name="booking_process"),
    path(
        "booking_success/<int:barber_id>/<str:date>/<str:time>/",
        BookingSuccessView.as_view(),
        name="booking_success",
    ),
]

core/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls", namespace="accounts")),
    path("", include("pages.urls")),
    path("booking/", include("booking.urls")),
    path("barbers/", include("barbers.urls")),
    path("customers/", include("customers.urls")),
    path("api/", include("rest_framework.urls")),
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/customers/urls.py
from django.urls import path
from .views import (
    CustomerPanelView,
    InvoiceDetailsView,
    CustomerEditProfile,
    CustomerChangePassword,
)

app_name = "customers"
urlpatterns = [
    path("", CustomerPanelView.as_view(), name="customer_panel"),
    path(
        "invoice-details",
        InvoiceDetailsView.as_view(),
        name="invoice_details",
    ),
    path(
        "editprofile",
        CustomerEditProfile.as_view(),
        name="edit_profile",
    ),
    path(
        "<int:customer_id>/change-password",
        CustomerChangePassword.as_view(),
        name="change_password",
    ),
]

core/booking/barbers/models.py
from django.db import models

core/booking/models.py
from django.db import models
from accounts.models import CustomerProfile, BarberProfile
# local
from .utils import Dateslotgenerator


from django.db import models
from django.core.exceptions import ValidationError
# 3rd party
from datetime import datetime


class TimeRange(models.Model):
    DAYS_OF_WEEK = (
        (0, "Saturday"),
        (1, "Sunday"),
        (2, "Monday"),
        (3, "Tuesday"),
        (4, "Wednesday"),
        (5, "Thursday"),
        (6, "Friday"),
    )

    barber = models.ForeignKey(BarberProfile, on_delete=models.CASCADE)

    Days = models.IntegerField(
        choices=DAYS_OF_WEEK,
    )

    workstart = models.TimeField()
    workfinish = models.TimeField()
    reststart = models.TimeField()
    restfinish = models.TimeField()
    duration = models.IntegerField(
        choices=(
            (15, "15 minute"),
            (30, "30 minute"),
            (45, "45 minute"),
            (60, "60 minute"),
        )
    )
    number_timeslots = models.IntegerField(null=True, blank=True)

    class Meta:
        unique_together = (
            "barber",
            "Days",
        )  # you can't have multiple appointments with the same barber on the same date and timeslot.

    def __str__(self):
        day_name = self.get_Days_display()
        return " {} ".format(
            day_name,
        )

    def get_day_name(self):
        return dict(self.DAYS_OF_WEEK).get(self.Days, "Unknown")


    def clean(self):
            if self.workstart >= self.workfinish:
                raise ValidationError({'workstart': 'Work start time must be earlier than or equal to work finish time.'})
            
            if self.reststart > self.restfinish:
                raise ValidationError({'reststart': 'Rest start time must be earlier than or equal to rest finish time.'})
            
            # If rest start and finish times are equal, it means no rest time is needed
            if (self.reststart != self.restfinish):
                # Additional validation: check if rest time falls within the work time range
                if self.reststart and self.restfinish:
                    if self.reststart < self.workstart or self.restfinish > self.workfinish:
                        raise ValidationError('Rest time must be within the work time range.')

class Booking(models.Model):
    barber = models.ForeignKey(BarberProfile, on_delete=models.CASCADE)
    date = models.DateField(choices=Dateslotgenerator())
    time = models.TimeField()
    customer = models.ForeignKey(CustomerProfile, on_delete=models.CASCADE,)

    STATUS_CHOICES = (
        ('cancelled', 'Cancelled'),
        ('confirmed', 'Confirmed'),
        ('pending', 'Pending'),
    )

    status = models.CharField(
        max_length=20, choices=STATUS_CHOICES, default="confirmed"
    )

    class Meta:
        unique_together = (
            "barber",
            "date",
            "time",
        )

    def __str__(self):
        return "{} {} {}. customer: {}".format(
            self.date, self.time, self.barber, self.customer
        )


class ExcludedDates(models.Model):
    barber = models.ForeignKey(BarberProfile, on_delete=models.CASCADE)

    date = models.DateField()

    class Meta:
        unique_together = (
            "date",
            "barber",
        )

    def __str__(self) -> str:
        return "{}".format(self.date, self.barber)

core/booking/forms.py
from django import forms
from .models import Booking


class BookingForm(forms.ModelForm):
    class Meta:
        model = Booking
        fields = ["date", "time", "barber"]
        
    def __init__(self, *args, **kwargs):
        self.customer = kwargs.pop("customer", None)
        super().__init__(*args, **kwargs)

    def clean(self):
        cleaned_data = super().clean()
        date = cleaned_data.get("date")
        barber = cleaned_data.get("barber")
        # if Booking.objects.filter(date = date,customer=self.customer,barber=barber).exists():
        #     self.add_error(
        #         None, "This time is already booked"
        #     )  # Add the error to a non-field, can also specify a field

        return cleaned_data

core/booking/barbers/views.py
# views.py
from django.views import View
from django.shortcuts import render
from accounts.models import BarberProfile
from booking.models import Booking, TimeRange
from datetime import datetime, timedelta
from .mixins import BarberProfilePermissionMixin


class BarberPanelView(BarberProfilePermissionMixin, View):
    def get(self, request, barber_id):
        barber = BarberProfile.objects.get(pk=barber_id)
        tomorrow_date = (datetime.today() + timedelta(days=1)).strftime("%Y-%m-%d")

        upcoming_bookings = Booking.objects.filter(
            barber=barber,
            date__gte=tomorrow_date,
        ).order_by("date", "time")
        count_tomorrow_bookings = upcoming_bookings.count()

        today_bookings = Booking.objects.filter(
            barber=barber,
            date=datetime.today().strftime("%Y-%m-%d"),
            time__gt=datetime.now(),
        ).order_by("time")

        count_today_bookings = today_bookings.count()

        context = {
            "barber": barber,
            "upcoming_bookings": upcoming_bookings,
            "today_bookings": today_bookings,
            "count_today_bookings": count_today_bookings,
            "count_tomorrow_bookings": count_tomorrow_bookings,
        }
        return render(request, "barbers/barber_panel.html", context)


class BarberScheduleView(BarberProfilePermissionMixin, View):
    def get(self, request, barber_id):
        barber = BarberProfile.objects.get(pk=barber_id)
        timerange = TimeRange.objects.filter(barber=barber)
        saturday = timerange.filter(Days=0)
        sunday = timerange.filter(Days=1)
        monday = timerange.filter(Days=2)
        tuesday = timerange.filter(Days=3)
        wednesday = timerange.filter(Days=4)
        thursday = timerange.filter(Days=5)
        friday = timerange.filter(Days=6)

        context = {
            "barber": barber,
            "timerange": timerange,
            "saturday": saturday,
            "sunday": sunday,
            "monday": monday,
            "tuesday": tuesday,
            "wednesday": wednesday,
            "thursday": thursday,
            "friday": friday,
        }
        return render(request, "barbers/barber_schedule.html", context)

core/booking/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views import View
from django.contrib import messages
from django.urls import reverse

# local
from .models import Booking, TimeRange, ExcludedDates
from .utils import TimeSlotgenerator, Dateslotgenerator
from accounts.models import BarberProfile
from .forms import BookingForm
from .mixins import BookingPermissionMixin

# 3rd party
from datetime import datetime
from datetime import date as datee


days_converter = {
    "Saturday": 0,
    "Sunday": 1,
    "Monday": 2,
    "Tuesday": 3,
    "Wednesday": 4,
    "Thursday": 5,
    "Friday": 6,
}


class BookingDateView(View):  # BookingPermissionMixin
    def get(self, request, barber_id):
        barber = get_object_or_404(BarberProfile, id=barber_id)
        check_timerange_day_exist = TimeRange.objects.filter(barber=barber)

        day_names_list = [
            str(timerange).strip() for timerange in check_timerange_day_exist #reteun day of week that barber setting that customer can reserve
        ]  # output: ['Sunday', 'Saturday', 'Wednesday', 'Friday', 'Thursday']
        all_days = [
            "Monday",
            "Tuesday",
            "Wednesday",
            "Thursday",
            "Friday",
            "Saturday",
            "Sunday",
        ]
        missing_days = set(all_days) - set(day_names_list)
        missing_days_list = list(missing_days)  # Days not in the list: for example barber doesn't set plan for friday because it's weekend

        exclude_dates = (
            ExcludedDates.objects.filter(  # days that barber  is not available
                barber=barber, date__gte=datee.today()
            )
        )
        exclude_dates_list = [
            exclude_date.date.strftime("%Y-%m-%d") for exclude_date in exclude_dates
        ]

        all_available_dates = Dateslotgenerator(  # return all available dates
            exclude_namedays=missing_days_list, exclude_dates=exclude_dates_list
        )
        # check that date is full timeslot  or not

        barber_timerange = TimeRange.objects.filter(barber=barber)
        print(barber,'barbername')
        print(barber_timerange)
        info_dict = {}

        for i in barber_timerange:
            info_dict[i.get_day_name()] = i.number_timeslots

        # Print the dictionary
        print("asa", info_dict)
        full_date = []

        for date in all_available_dates:  # all_da
            date = date[0]
            date_deform = date.strftime("%Y-%m-%d")  # Convert datetime.date to string
            date_name = date.strftime("%A")
            count_active_reserve = Booking.objects.filter(
                barber=barber, date=date_deform
            ).count()

            if date_name in info_dict:
                print(
                    "count_active_reserve:",
                    count_active_reserve,
                    info_dict[date_name],
                    "info_dict[date_name]",
                    date_name,
                )
                if count_active_reserve == info_dict[date_name]:
                    full_date.append(date_deform)

        print("Full date:", full_date)
        return render(
            request,
            "booking/booking_date.html",
            {
                "all_dateslot": all_available_dates,
                "full_date": full_date,
                "barber": barber,
            },
        )


class BookingTimeView(View):  # BookingPermissionMixin
    template_name = "booking/booking_time.html"

    def post(self, request, barber_id):
        date = request.POST.get("selected_date")
        date_format = datetime.strptime(
            date, "%Y-%m-%d"
        )  # change format of date to valid format (str)
        name_of_day = date_format.strftime("%A")  # retuen for a example friday

        barber = get_object_or_404(BarberProfile, id=barber_id)

        timeslots_selected_date = TimeRange.objects.filter(  # retuen all range timeslot for day that selected ( for a example show time slot for tuesday )
            barber=barber,
            Days=days_converter[name_of_day],  # Days=self.days_converter[name_of_day]
        )
        reserved_timeslot = Booking.objects.filter(
            barber=barber, date=date
        )  # return all query for reserved timeslot

        reserved_timeslot_format = [
            booking.time.strftime("%H:%M") for booking in reserved_timeslot
        ]  # reformat  return all query for reserved timeslot

        if timeslots_selected_date.exists():
            first_timeslot = timeslots_selected_date.first()

            all_timeslot = TimeSlotgenerator(
                first_timeslot.workstart.strftime("%H:%M"),
                first_timeslot.workfinish.strftime("%H:%M"),
                first_timeslot.reststart.strftime("%H:%M"),
                first_timeslot.restfinish.strftime("%H:%M"),
                first_timeslot.duration,
            )

        else:
            print("No timeslots found for the specified conditions.")

        # TODO  is better  check time past or not by fronted developer not back end

        today = datee.today()
        our_date = datetime.strptime(date, "%Y-%m-%d").date()
        if our_date == today:
            current_time = datetime.now().time()
            all_timeslot_times = [datetime.strptime(time_str, '%H:%M').time() for time_str in all_timeslot[0]]
            past_time_slots = [
                time_slot.strftime("%H:%M")
                for time_slot in all_timeslot_times
                if time_slot < current_time
            ]
        else:
            past_time_slots = []

        return render(
            request,
            self.template_name,
            {
                "barber": barber,
                "selected_date": date,
                "day_of_week": name_of_day,
                "all_timeslot": all_timeslot[0],
                "all_reserve": reserved_timeslot_format,
                "past_time_slots": past_time_slots,
            },
        )


class BookingProccessView(BookingPermissionMixin, View):
    template_name = "booking/booking_proccess.html"

    def post(self, request):
        form = BookingForm(request.POST, customer=request.user.customerprofile)
        print(request.user.customerprofile)
        print(request.POST.get("barber"))
        print()

        if form.is_valid():
            customer = request.user.customerprofile
            barber_id = request.POST.get("barber")
            barber = get_object_or_404(BarberProfile, id=barber_id)
            time = request.POST.get("time")
            date = request.POST.get("date")
            # start save booking
            new_booking = form.save(commit=False)
            new_booking.customer = customer
            new_booking.barber = barber
            new_booking.time = time
            new_booking.date = date
            new_booking.save()
            messages.success(
                request, "you reserved appointment successfully", "success"
            )
            return redirect(
                reverse(
                    "booking:booking_success",
                    kwargs={"barber_id": barber_id, "date": date, "time": time},
                )
            )
        else:
            messages.error(
                request,
                "you have active reservation with this barber on this  date ",
                "danger",
            )
            barber_id = request.POST.get("barber")
            print(request.path)
            return redirect(
                reverse("booking:booking_date", kwargs={"barber_id": barber_id})
            )


class BookingSuccessView(BookingPermissionMixin, View):
    template_name = "booking/booking_success.html"

    def get(self, request, barber_id, date, time):
        barber = get_object_or_404(BarberProfile, id=barber_id)

        return render(
            request,
            self.template_name,
            {
                "barber": barber,
                "date": date,
                "time": time,
            },
        )

core/templates/booking/booking_date.html
{% extends '_base.html' %}
{% load static %}

{% block content %}
<div class="main-wrapper">

    {% include 'include/_header.html' %} <!-- add header -->


    <div class="breadcrumb-bar">
        <div class="container-fluid">
            <div class="row align-items-center">
                <div class="col-md-12 col-12">
                    <nav aria-label="breadcrumb" class="page-breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="index-2.html">Home</a></li>
                            <li class="breadcrumb-item active" aria-current="page">Booking</li>
                        </ol>
                    </nav>
                    <h2 class="breadcrumb-title">Booking</h2>
                </div>
            </div>
        </div>
    </div>
    {% include 'include/messages.html' %}



    <div class="content">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-body">
                            <div class="booking-doc-info">
                                <a href="doctor-profile.html" class="booking-doc-img">
                                    <img src="{{ barber.image.url }}" alt="User Image">
                                </a>
                                <div class="booking-info">
                                    <h4><a href="doctor-profile.html">{{ barber.user.last_name }}</a></h4>

                                    <p class="text-muted mb-0"><i class="fas fa-map-marker-alt"></i> IRAN, Tehran
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-12 col-sm-4 col-md-6">
                            <h4 class="mb-1"></h4>
                            <p class="text-muted">Monday</p>
                        </div>
            
                    </div>

                    <div class="card booking-schedule schedule-widget">

                            
                            <!-- time slot TODO -->
                            <div class="schedule-cont">
                                <div class="row">
                                    <div class="col-md-12">
                                        <div class="time-slot">
                                            <ul class="clearfix">
                                                {% for date in all_dateslot %}

                                                <li>
                                                    <div class="date-slot">
                                                        {% if date.0|date:"Y-m-d" in full_date %}
                                                        <button class="timing"
                                                            style="   background-color: #979A9A"
                                                            disabled>
                                                            <span style="font-size: 10px;">{{ date.0|date:"D" }}</span><br>
                                                            <span>{{ date.0|date:"Y-m-d" }}</span>

                                                        </button>
                                                        {% else %}
                                                        <button class="timing">
                                                            <span style="font-size: 10px;">{{ date.0|date:"D" }}</span><br>
                                                            <span>{{ date.0|date:"Y-m-d" }}</span>
                                                        </button>
                                                        {% endif %}
                                                        </br>

                                                    </div>


                                                </li>
                                                {% endfor %}

                                            </ul>
                                        </div>
                                    </div>
                                </div>
                            </div>




                    </div>

                        <form id="bookingForm" method="post" action="{% url 'booking:booking_time' barber.pk  %}">
                            {% csrf_token %}

                            <input type="hidden" id="selectedDate" name="selected_date" value="" autocomplete="off" />
                            <!-- Your slot selection code here -->

                            <div class="submit-section proceed-btn text-end">
                                <button type="submit" class="btn btn-primary submit-btn" id="proceedToPayBtn">Proceed to
                                    Pay</button>
                            </div>
                        </form>





                </div>
            </div>
        </div>
    </div>

    {% include 'include/_scripts.html' %}

<script>
    $(document).ready(function () {
        $('.timing').click(function () {
            // Remove the 'selected' class from all slots
            $('.timing').removeClass('selected');

            // Add the 'selected' class to the clicked slot
            $(this).addClass('selected');

            // Extract and set the selected date
            var selectedSlot = $(this).text().trim();
            var parts = selectedSlot.split(/\s+/); // Split by spaces

            var date = parts[1];
            $('#selectedDate').val(date);

            // Enable or disable the "Proceed to Pay" button based on selection
            toggleProceedToPayButton();
        });

        function toggleProceedToPayButton() {
            // Check if any date slot is selected
            var selectedDate = $('#selectedDate').val();
            if (selectedDate) {
                // Enable the button if a date slot is selected
                $('#proceedToPayBtn').prop('disabled', false);
            } else {
                // Disable the button if no date slot is selected
                $('#proceedToPayBtn').prop('disabled', true);
            }
        }

        // Initial check on page load
        toggleProceedToPayButton();
    });
</script>


    {% endblock content %}

core/templates/booking/booking_proccess.html
{% extends '_base.html' %}
{% load static %}

{% block content %}
<div class="main-wrapper">

    {% include 'include/_header.html' %} <!-- add header -->

    <div class="breadcrumb-bar">
        <div class="container-fluid">
            <div class="row align-items-center">
                <div class="col-md-12 col-12">
                    <nav aria-label="breadcrumb" class="page-breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="index-2.html">Home</a></li>
                            <li class="breadcrumb-item active" aria-current="page">Booking</li>
                        </ol>
                    </nav>
                    <h2 class="breadcrumb-title">Booking</h2>
                </div>
            </div>
        </div>
    </div>
    {% include 'include/messages.html' %}



    <div class="content success-page-cont">
        <div class="container-fluid">
            <div class="row justify-content-center">
                <div class="col-lg-6">

                    <div class="card success-card">
                        <div class="card-body">
                            <div class="success-cont">
                                <i class="fas fa-check"></i>
                                <h3>Appointment booked Successfully!</h3>
                                <p>Appointment booked with <strong>{{ barber }}</strong><br> on <strong>{{ date }} at {{
                                        time }}</strong></p>
                                <a href="{% url 'customers:invoice_details' %}"
                                    class="btn btn-primary view-inv-btn">View Invoice</a>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>


</div>


{% endblock content %}

core/templates/booking/booking_success.html
{% extends '_base.html' %}
{% load static %}

{% block content %}
    <div class="main-wrapper">

    {% include 'include/_header.html' %} <!-- add header -->

        <div class="breadcrumb-bar">
            <div class="container-fluid">
                <div class="row align-items-center">
                    <div class="col-md-12 col-12">
                        <nav aria-label="breadcrumb" class="page-breadcrumb">
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item"><a href="index-2.html">Home</a></li>
                                <li class="breadcrumb-item active" aria-current="page">Booking</li>
                            </ol>
                        </nav>
                        <h2 class="breadcrumb-title">Booking</h2>
                    </div>
                </div>
            </div>
        </div>
        {% include 'include/messages.html' %}



        <div class="content success-page-cont">
            <div class="container-fluid">
                <div class="row justify-content-center">
                    <div class="col-lg-6">

                        <div class="card success-card">
                            <div class="card-body">
                                <div class="success-cont">
                                    <i class="fas fa-check"></i>
                                    <h3>Appointment booked Successfully!</h3>
                                    <p>Appointment booked with <strong>{{ barber }}</strong><br> on <strong>{{ date }} at {{ time }}</strong></p>
                                    <a href="{% url 'customers:invoice_details' %}" class="btn btn-primary view-inv-btn">View Invoice</a>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>


    </div>


{% endblock content %}