core/accounts/urls.py
from django.urls import path
from .views import RegisterView
from .views import (
    ChangePasswordView,
    PasswordChangedView,
    UserRegisterVerifyCodeView,
    UserLoginView,
    UserLogoutView,
)

app_name = "accounts"

urlpatterns = [
    path("login/", UserLoginView.as_view(), name="user_login"),
    path("logout/", UserLogoutView.as_view(), name="user_logout"),
    path("register/", RegisterView.as_view(), name="register"),
    path("change-password/", ChangePasswordView.as_view(), name="change_password"),
    path("password-changed/", PasswordChangedView.as_view(), name="password_changed"),
    path("verify/", UserRegisterVerifyCodeView.as_view(), name="verify_code"),
    path(
        "forget-password/", UserRegisterVerifyCodeView.as_view(), name="forget_password"
    ),
]

core/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls", namespace="accounts")),
    path("", include("pages.urls")),
    path("booking/", include("booking.urls")),
    path("barbers/", include("barbers.urls")),
    path("customers/", include("customers.urls")),
    path("api/", include("rest_framework.urls")),
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from django.core.validators import RegexValidator
from django.contrib.auth.models import BaseUserManager

# local
from .managers import UserManager


class User(AbstractBaseUser, PermissionsMixin):

    class Role(models.TextChoices):
        CUSTOMERUSER = "CUSTOMERUSER", "CustomerUser"
        BARBERUSER = "BARBERUSER", "BarberUser"
        ADMIN = "ADMIN", "Admin"

    base_role = Role.ADMIN

    phone_number = models.CharField(
        max_length=11,
        validators=[RegexValidator(r"^\d{2}$", "Enter a valid 2-digit phone number.")],
        unique=True,
    )
    first_name = models.CharField(max_length=255, blank=True)
    last_name = models.CharField(max_length=255, blank=False, null=False)
    email = models.EmailField(max_length=255, blank=True, null=True, unique=True)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)
    birthday = models.DateField(null=True, blank=True)
    date_joined = models.DateTimeField(auto_now_add=True)
    role = models.CharField(max_length=50, choices=Role.choices)

    USERNAME_FIELD = "phone_number"

    objects = UserManager()

    def save(self, *args, **kwargs):
        if not self.pk:
            self.role = self.base_role
        return super().save(*args, **kwargs)

    def __str__(self):
        return self.phone_number


class CustomerUserManager(BaseUserManager):
    def get_queryset(self, *args, **kwargs):
        results = super().get_queryset(*args, **kwargs)
        return results.filter(role=User.Role.CUSTOMERUSER)


class CustomerUser(User):
    base_role = User.Role.CUSTOMERUSER
    customeruser = CustomerUserManager()

    class Meta:
        proxy = True

    def welcome(self):
        return "Only for CUSTOMERS"


class BarberUSERManager(BaseUserManager):
    def get_queryset(self, *args, **kwargs):
        results = super().get_queryset(*args, **kwargs)
        return results.filter(role=User.Role.BARBERUSER)


class CustomerProfile(models.Model):
    user = models.OneToOneField(
        User, on_delete=models.CASCADE, related_name="customerprofile"
    )
    image = models.ImageField(upload_to="customers/", default="customers/default.jpg")

    def __str__(self):
        return self.user.phone_number

    def delete(self, *args, **kwargs):
        # Delete associated BarberUser
        customer_user = CustomerProfile.objects.filter(id=self.user.id)
        if customer_user.exists():
            customer_user.delete()

        # Call the parent class delete method
        super().delete(*args, **kwargs)


class BarberUser(User):
    base_role = User.Role.BARBERUSER
    barberuser = BarberUSERManager()

    class Meta:
        proxy = True

    def welcome(self):
        return "Only for barbers"


class BarberProfile(models.Model):
    user = models.OneToOneField(
        User, on_delete=models.CASCADE, related_name="barberprofile"
    )
    image = models.ImageField(upload_to="barbers/", default="barbers/default.jpg")
    reservation_system = models.BooleanField(default=False)

    def __str__(self):
        return self.user.phone_number

    def delete(self, *args, **kwargs):
        # Delete associated BarberUser
        barber_user = BarberUser.objects.filter(id=self.user.id)
        if barber_user.exists():
            barber_user.delete()

        super().delete(*args, **kwargs)


class OtpCode(models.Model):
    phone_number = models.CharField(max_length=11, unique=True)
    code = models.PositiveSmallIntegerField()
    created = models.DateTimeField(auto_now_add=True)
    expiration = models.DateTimeField

    def __str__(self) -> str:
        return f"{self.phone_number} - {self.code} - {self.created}"

core/accounts/forms.py
# forms.py
from django import forms
from .models import User, OtpCode, CustomerUser
from django.core.exceptions import ValidationError
from django.core.validators import RegexValidator  # Import RegexValidator from django.core.validators


class ChangePasswordForm(forms.Form):
    old_password = forms.CharField(label="Old Password", widget=forms.PasswordInput)
    new_password = forms.CharField(label="New Password", widget=forms.PasswordInput)
    repeat_new_password = forms.CharField(
        label="Repeat New Password", widget=forms.PasswordInput
    )

    def clean(self):
        cleaned_data = super().clean()
        new_password = cleaned_data.get("new_password")
        repeat_new_password = cleaned_data.get("repeat_new_password")

        if new_password != repeat_new_password:
            raise forms.ValidationError("New passwords do not match.")

        return cleaned_data


class UserRegisterForm(forms.Form):
    phone_number = forms.CharField(
        required=True,  # Ensures the field is not null
        validators=[
            RegexValidator(r"^\d{2}$", "Enter a valid 2-digit phone number.")
        ],
    )
    
    password = forms.CharField(
        required=True,  # Ensures the field is not null
        widget=forms.PasswordInput,
    )
    def clean_phone_number(self):
        phone = self.cleaned_data['phone_number']

        user = CustomerUser.objects.filter(phone_number=phone).exists()
        if user:
            raise ValidationError('This phone number already exists')
        OtpCode.objects.filter(phone_number=phone).delete()
        return phone


class verifyCodeForm(forms.Form):
    code = forms.IntegerField(required=True)

    def clean_code(self):
        code = self.cleaned_data['code']
        if not code:
            raise forms.ValidationError("Code field cannot be empty.")

        return code


class UserLoginForm(forms.Form):
    phone_number = forms.CharField(required=True)
    password = forms.CharField(widget=forms.PasswordInput, required=True)
    
    def clean_phone_number(self):
        phone = self.cleaned_data['phone_number']
        user = CustomerUser.objects.filter(phone_number=phone).exists()
        if not user:
            raise ValidationError('This phone number does not exist')
        return phone
    
    def clean_password(self):
        password = self.cleaned_data['password']
        if not password:
            raise forms.ValidationError("Password field cannot be empty.")
        return password
    

core/accounts/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import FormView
from django.urls import reverse_lazy
from django.contrib import messages
from .forms import ChangePasswordForm
from django.views.generic.base import TemplateView
from django.contrib import messages
from django.contrib.auth.hashers import check_password
from django.shortcuts import render, redirect
from django.views import View
from django.contrib.auth import login, logout, authenticate

# local
from .models import OtpCode
from .forms import UserRegisterForm, verifyCodeForm, UserLoginForm
from .models import CustomerUser
from .utils import sent_otp_code

# 3rd party
import random


class UserLoginView(View):
    form_class = UserLoginForm
    template_name = "accounts/login.html"

    def get(self, request):
        form = self.form_class()
        return render(request, self.template_name, {"form": form})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(
                request, phone_number=cd["phone_number"], password=cd["password"]
            )
            if user is not None:
                login(request, user)
                messages.success(request, "You logged in successfully.", "info")
                return redirect("pages:home")
            else:
                # Display error message if authentication fails
                form.add_error(None, "Phone number or password is incorrect.")
                messages.error(
                    request, "Phone number or password is incorrect.", "warning"
                )
        return render(request, self.template_name, {"form": form})


class UserLogoutView(LoginRequiredMixin, View):
    def get(self, request):
        logout(request)
        messages.success(request, "you logged out successfully", "success")
        return redirect("pages:home")


class RegisterView(View):
    template_name = "accounts/register.html"
    success_url = reverse_lazy("pages:home")
    form_class = UserRegisterForm

    def get(self, request, *args, **kwargs):
        form = self.form_class()
        return render(request, self.template_name, {"form": form})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)

        if form.is_valid():

            random_code = random.randint(10000, 99999)
            sent_otp_code(form.cleaned_data["phone_number"], random_code)
            OtpCode.objects.create(
                phone_number=form.cleaned_data["phone_number"], code=random_code
            )

            request.session["user_registeration_form_info"] = {
                "phone_number": form.cleaned_data["phone_number"],
                "password": form.cleaned_data["password"],
                "code": random_code,
            }

            messages.success(
                request,
                "An activation code has been sent to your phone number.",
                "success",
            )
            return redirect("accounts:verify_code")
        else:
            return render(request, self.template_name, {"form": form})


class UserRegisterVerifyCodeView(View):
    template_name = "accounts/verify_code.html"
    form_class = verifyCodeForm

    def get(self, request, *args, **kwargs):
        form = self.form_class
        code_instance = OtpCode.objects.get(
            phone_number=request.session["user_registeration_form_info"]["phone_number"]
        )
        created_time = code_instance.created.time()
        created_time = created_time.strftime("%H:%M:%S")
        context = {"form": form, "created_time": created_time}
        return render(
            request, self.template_name, context
        )  # Pass the form to the template context

    def post(self, request, *args, **kwargs):
        user_session = request.session["user_registeration_form_info"]
        code_instance = OtpCode.objects.get(phone_number=user_session["phone_number"])
        form = self.form_class(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            if cd["code"] == code_instance.code:
                # create customer user
                CustomerUser.objects.create_user(
                    user_session["phone_number"],
                    user_session["password"],
                )

                code_instance.delete()
                messages.success(request, "you registered successfully", "success")
                return redirect("pages:home")

            else:
                form.add_error("code", "this code is wrong")
                messages.error(request, "this code is wrong", "danger")
                code_instance = OtpCode.objects.get(
                    phone_number=request.session["user_registeration_form_info"][
                        "phone_number"
                    ]
                )
                created_time = code_instance.created.time()
                created_time = created_time.strftime("%H:%M:%S")
                context = {"form": form, "created_time": created_time}
                return render(
                    request, self.template_name, context
                )  # Pass the form to the template context

        else:
            return render(request, self.template_name, {"form": form})


class ChangePasswordView(LoginRequiredMixin, FormView):
    template_name = "accounts/change_password.html"
    success_url = reverse_lazy("pages:home")
    form_class = ChangePasswordForm

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        if form.is_valid():
            old_password = form.cleaned_data["old_password"]
            new_password = form.cleaned_data["new_password"]
            print("new password", new_password)
            print("old password", old_password)

            user = request.user

            if not check_password(old_password, user.password):
                messages.error(request, "Old password is incorrect.")
                form.add_error("old_password", "Old password is incorrect.")
                return self.form_invalid(form)

            user.set_password(new_password)
            user.save()

            messages.success(request, "Password changed successfully.")
            return self.form_valid(form)
        else:

            return self.form_invalid(form)


class PasswordChangedView(TemplateView):
    template_name = "pages/home.html"

core/templates/accounts/change_password.html
{% extends '_base.html' %}
{% load static %}

{% block content %}

<div class="main-wrapper">
    {% include 'include/_header.html' %} <!-- add header -->


    <div class="breadcrumb-bar">
        <div class="container-fluid">
            <div class="row align-items-center">
                <div class="col-md-12 col-12">
                    <nav aria-label="breadcrumb" class="page-breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="index-2.html">Home</a></li>
                            <li class="breadcrumb-item active" aria-current="page">Change Password</li>
                        </ol>
                    </nav>
                    <h2 class="breadcrumb-title">Change Password</h2>
                </div>
            </div>
        </div>
    </div>


    <div class="content">
        <div class="container-fluid">
            <div class="row">
                {% include 'include/cus_panel_sidebar.html' %}

                <div class="col-md-7 col-lg-8 col-xl-9">
                    <div class="card">
                        <div class="card-body">
                            <div class="row">
                                <div class="col-md-12 col-lg-6">

                                    <form method="post">
                                        {% csrf_token %}
                                        <div class="form-group">
                                            <label for="id_old_password">Old Password</label>

                                            <input type="password" class="form-control"  name="{{ form.old_password.name }}">
                                        </div>
                                        <div class="form-group">
                                            <label for="id_new_password">New Password</label>
                                            <input type="password" class="form-control" name="{{ form.new_password.name }}">
                                        </div>
                                        <div class="form-group">
                                            <label for="id_repeat_new_password">Confirm Password</label>
                                            <input type="password" class="form-control" name="{{ form.repeat_new_password.name }}">
                                        </div>
                                        <div class="submit-section">
                                            <button type="submit" class="btn btn-primary submit-btn">Save Changes</button>
                                        </div>
                                            {% if form.old_password.errors %}
                                            <span class="error">{{ form.old_password.errors }}</span>
                                            {% endif %}
                                            {% if form.new_password.errors %}
                                            <span class="error">{{ form.new_password.errors }}</span>
                                            {% endif %}
                                            {% if form.repeat_new_password.errors %}
                                            <span class="error">{{ form.repeat_new_password.errors }}</span>
                                            {% endif %}
                    
                                    </form>
                                
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>



</div>


{% endblock content %}

core/templates/accounts/login.html
{% extends '_base.html' %}
{% load static %}


{% block content %}



<div class="main-wrapper">

    {% include 'include/_header.html' %} <!-- add header -->



    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-8 offset-md-2">

                    <div class="account-content">
                        <div class="row align-items-center justify-content-center">
                            <div class="col-md-7 col-lg-6 login-left">
                                <img src="{% static 'img/registeration/login.png' %}" class="img-fluid"
                                    alt="Doccure Login">
                            </div>
                            <div class="col-md-12 col-lg-6 login-right">
                                <div class="login-header">
                                    <h3>Login <span>Doccure</span></h3>
                                </div>




                                <form method="post">
                                    {% csrf_token %}
                                    <div class="form-group form-focus">
                                        <input type="tel" class="form-control floating"
                                            oninput="this.value = this.value.replace(/[^0-9]/g, '').slice(0, 11)"
                                            name="{{ form.phone_number.name }}">
                                        <label class="focus-label">Phone number</label>
                                    </div>
                                    <div class="form-group form-focus">
                                        <input type="password" class="form-control floating"
                                            name="{{ form.password.name }}">
                                        <label class="focus-label">Password</label>
                                    </div>
                                    <div class="text-end">
                                        <a class="forgot-link" href="forgot-password.html">Forgot Password ?</a>
                                    </div>
                                    <button class="btn btn-primary w-100 btn-lg login-btn" type="submit">Login</button>
                                    <div class="login-or">
                                        <span class="or-line"></span>
                                        <span class="span-or">or</span>
                                    </div>

                                    <div class="text-center dont-have">Don’t have an account? <a
                                            href="{% url 'accounts:register' %}">Register</a></div>
                                </form>
                                {{ form.errors }}
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>




</div>




{% endblock content %}

core/templates/accounts/password-reset-done.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1 style="color: red;">salm</h1>
</body>
</html>

core/templates/accounts/register.html
{% extends '_base.html' %}
{% load static %}


{% block content %}



<div class="main-wrapper">

    {% include 'include/_header.html' %} <!-- add header -->


        <div class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-8 offset-md-2">

                        <div class="account-content">
                            <div class="row align-items-center justify-content-center">
                                <div class="col-md-7 col-lg-6 login-left">
                                    <img src="{% static 'img/registeration/signup.jpg' %}" class="img-fluid" alt="Doccure Register">
                                </div>
                                <div class="col-md-12 col-lg-6 login-right">
                                    <div class="login-header">
                                        <h3>Patient Register <a href="doctor-register.html">Are you a Doctor?</a></h3>
                                    </div>

                                    <form method="post">
                                        {% csrf_token %}
                                        <!-- <div class="form-group form-focus">
                                            <input type="text" class="form-control floating">
                                            <label class="focus-label">Name</label>
                                        </div> -->
                                        <div class="form-group form-focus">
                                            <input type="tel" class="form-control floating" oninput="this.value = this.value.replace(/[^0-9]/g, '').slice(0, 11)"  name="{{ form.phone_number.name }}">
                                            <label class="focus-label">Mobile Number</label>
                                        </div>
                                        <div class="form-group form-focus">
                                            <input type="password" class="form-control floating" name="{{ form.password.name }}" >
                                            <label class="focus-label">Create Password</label>
                                        </div>
                                        <!-- <div class="terms-and-policy pt-2 pb-2">
                                            <input type="checkbox" required name="checkbox" value="check"
                                                id="agree" /><span class="agree">I agree to these <span class="terms"><a
                                                        href="term-condition.html" target="_blank">Terms of Use</a> and
                                                    <a href="privacy-policy.html" target="_blank">Privacy
                                                        Policy</a></span></span>
                                        </div> -->
                                        <div class="text-end">
                                            <a class="forgot-link" href="{% url 'accounts:user_login' %}">Already have an account?</a>
                                        </div>
                                        <button class="btn btn-primary w-100 btn-lg login-btn"
                                            type="submit">Signup</button>
                                        <div class="login-or">
                                            <span class="or-line"></span>
                                        </div>
                                        
                                    </form>
                                    {{ form.errors }}

                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>


    </div>
{% endblock content %}

core/templates/accounts/register_test.html
{% extends '_base.html' %}
{% load static %}


{% block content %}
<p>
    hello
</p>

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit"/>
</form>
{% endblock content %}

core/templates/accounts/verify_code.html
{% extends '_base.html' %}
{% load static %}

{% block content %}
<!-- hide arrow of input tag for number -->
<style>
    input::-webkit-outer-spin-button,
    input::-webkit-inner-spin-button {
        display: none;
    }
</style>

<div class="main-wrapper">
    {% include 'include/_header.html' %} <!-- add header -->

    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-8 offset-md-2">
                    <div class="account-content">
                        <div class="row align-items-center justify-content-center">
                            <div class="col-md-7 col-lg-6 login-left">
                                <img src="{% static 'img/registeration/signup.jpg' %}" class="img-fluid"
                                    alt="Login Banner">
                            </div>
                            <div class="col-md-12 col-lg-6 login-right">
                                <div class="login-header">
                                    <h3>Enter Code</h3>
                                    <p class="small text-muted">Enter code that was sent by SMS</p>
                                </div>

                                <form method="post">{% csrf_token %}

                                    <div class="form-group form-focus">
                                        <label class="focus-label">Activation code</label>
                                        <input type="number" class="form-control floating" name="{{ form.code.name }}"
                                            oninput="this.value = this.value.replace(/[^0-9]/g, '').slice(0, 5)">
                                    </div>
                                    <button class="btn btn-primary w-100 btn-lg login-btn"
                                        type="submit">Register</button>
                                </form>
                                {{ form.errors }}

                                <div id="countdown"></div>
                                <div id="startTime"></div>



                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<script>
    // Retrieve time from Django and convert it to a JavaScript Date object
    // var djangoTime = "22:49:00"; 
    var djangoTime = "{{ created_time }}"; // Replace this with the time retrieved from Django
    console.log(djangoTime)
    var djangoTimeParts = djangoTime.split(':');
    var targetTime = new Date();
    targetTime.setHours(parseInt(djangoTimeParts[0], 10));
    targetTime.setMinutes(parseInt(djangoTimeParts[1], 10));
    targetTime.setSeconds(parseInt(djangoTimeParts[2], 10));

    // Add 2 minutes to the target time
    targetTime.setMinutes(targetTime.getMinutes() + 2);

    // Function to update the countdown timer
    function updateCountdown() {
        var currentTime = new Date();
        var timeDifference = targetTime - currentTime;

        if (timeDifference <= 0) {
            document.getElementById('countdown').innerHTML = "<a href='#' onclick='window.location.reload();'>Reset</a>";
        } else {
            var minutes = Math.floor((timeDifference % (1000 * 60 * 60)) / (1000 * 60));
            var seconds = Math.floor((timeDifference % (1000 * 60)) / 1000);

            // Format the remaining time
            var remainingTime = "";
            if (minutes > 0) {
                remainingTime += minutes + "m ";
            }
            remainingTime += seconds + "s";

            document.getElementById('countdown').innerHTML = remainingTime;
            setTimeout(updateCountdown, 1000);
        }
    }

    updateCountdown();
</script>


{% endblock content %}