core/accounts/urls.py
from django.urls import path
from .views import RegisterView
from .views import (
    ChangePasswordView,
    PasswordChangedView,
    UserRegisterVerifyCodeView,
    UserLoginView,
    UserLogoutView,
)

app_name = "accounts"

urlpatterns = [
    path("login/", UserLoginView.as_view(), name="user_login"),
    path("logout/", UserLogoutView.as_view(), name="user_logout"),
    path("register/", RegisterView.as_view(), name="register"),
    path("change-password/", ChangePasswordView.as_view(), name="change_password"),
    path("password-changed/", PasswordChangedView.as_view(), name="password_changed"),
    path("verify/", UserRegisterVerifyCodeView.as_view(), name="verify_code"),
    path(
        "forget-password/", UserRegisterVerifyCodeView.as_view(), name="forget_password"
    ),
]

core/booking/barbers/urls.py
from django.urls import path
from .views import BarberPanelView, BarberScheduleView

app_name = "barbers"
urlpatterns = [
    path("<int:barber_id>", BarberPanelView.as_view(), name="barber_panel"),
    path(
        "<int:barber_id>/barber-schedule/",
        BarberScheduleView.as_view(),
        name="barber_schedule",
    ),
]

core/booking/urls.py
from django.urls import path

from .views import (
    BookingDateView,
    BookingTimeView,
    BookingSuccessView,
    BookingProccessView,
)

app_name = "booking"

urlpatterns = [
    path("<int:barber_id>/", BookingDateView.as_view(), name="booking_date"),
    path("<int:barber_id>/time/", BookingTimeView.as_view(), name="booking_time"),
    path("booking_proccessing", BookingProccessView.as_view(), name="booking_process"),
    path(
        "booking_success/<int:barber_id>/<str:date>/<str:time>/",
        BookingSuccessView.as_view(),
        name="booking_success",
    ),
]

core/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls", namespace="accounts")),
    path("", include("pages.urls")),
    path("booking/", include("booking.urls")),
    path("barbers/", include("barbers.urls")),
    path("customers/", include("customers.urls")),
    path("api/", include("rest_framework.urls")),
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/customers/urls.py
from django.urls import path
from .views import (
    CustomerPanelView,
    InvoiceDetailsView,
    CustomerEditProfile,
    CustomerChangePassword,
)

app_name = "customers"
urlpatterns = [
    path("", CustomerPanelView.as_view(), name="customer_panel"),
    path(
        "invoice-details",
        InvoiceDetailsView.as_view(),
        name="invoice_details",
    ),
    path(
        "editprofile",
        CustomerEditProfile.as_view(),
        name="edit_profile",
    ),
    path(
        "<int:customer_id>/change-password",
        CustomerChangePassword.as_view(),
        name="change_password",
    ),
]

core/pages/urls.py
from django.urls import path
from .views import HomePageView, TestPageView, ListBarberPageView, ComponentPageView

app_name = "pages"

urlpatterns = [
    path("", HomePageView.as_view(), name="home"),
    path("test/", TestPageView.as_view(), name="test"),
    path("list_barber/", ListBarberPageView.as_view(), name="list_barber"),
    path("components/", ComponentPageView.as_view(), name="components"),
]

core/booking/barbers/models.py
from django.db import models

core/booking/barbers/views.py
# views.py
from django.views import View
from django.shortcuts import render
from accounts.models import BarberProfile
from booking.models import Booking, TimeRange
from datetime import datetime, timedelta
from .mixins import BarberProfilePermissionMixin


class BarberPanelView(BarberProfilePermissionMixin, View):
    def get(self, request, barber_id):
        barber = BarberProfile.objects.get(pk=barber_id)
        tomorrow_date = (datetime.today() + timedelta(days=1)).strftime("%Y-%m-%d")

        upcoming_bookings = Booking.objects.filter(
            barber=barber,
            date__gte=tomorrow_date,
        ).order_by("date", "time")
        count_tomorrow_bookings = upcoming_bookings.count()

        today_bookings = Booking.objects.filter(
            barber=barber,
            date=datetime.today().strftime("%Y-%m-%d"),
            time__gt=datetime.now(),
        ).order_by("time")

        count_today_bookings = today_bookings.count()

        context = {
            "barber": barber,
            "upcoming_bookings": upcoming_bookings,
            "today_bookings": today_bookings,
            "count_today_bookings": count_today_bookings,
            "count_tomorrow_bookings": count_tomorrow_bookings,
        }
        return render(request, "barbers/barber_panel.html", context)


class BarberScheduleView(BarberProfilePermissionMixin, View):
    def get(self, request, barber_id):
        barber = BarberProfile.objects.get(pk=barber_id)
        timerange = TimeRange.objects.filter(barber=barber)
        saturday = timerange.filter(Days=0)
        sunday = timerange.filter(Days=1)
        monday = timerange.filter(Days=2)
        tuesday = timerange.filter(Days=3)
        wednesday = timerange.filter(Days=4)
        thursday = timerange.filter(Days=5)
        friday = timerange.filter(Days=6)

        context = {
            "barber": barber,
            "timerange": timerange,
            "saturday": saturday,
            "sunday": sunday,
            "monday": monday,
            "tuesday": tuesday,
            "wednesday": wednesday,
            "thursday": thursday,
            "friday": friday,
        }
        return render(request, "barbers/barber_schedule.html", context)

core/templates/include/_barbers.html
{% load static %}
<section class="cosmetics-specialist">
    <div class="container">
        <div class="section-title text-center">
            <h2>choose your Barber specialist</h2>
            <p>booking  an appontment  immediatly</p>
        </div>
        <div class="row justify-content-center">
            {% for barber in barbers %}
            <div class="col-12 col-md-6 col-lg-3">
                <div class="specialities-col">
                    <div class="card">
                        <a href="doctor-profile.html" class="specialities-img">
                            <img src="{{ barber.image.url }}" alt="" style="max-width: 500px; max-height: 500px;">
                        </a>
                        <div class="card-body">
                            <div class="specialities-content">
                                <a href="doctor-profile.html">
                                    <h5>{{ barber.user.last_name }}</h5>
                                </a>
                                <p>MBBS, MDS - Cosmetics Surgeon</p>
                                {% if barber.user.barberprofile.reservation_system %}
                                <a href="{% url 'booking:booking_date'  barber.pk %}" class="booknow-btn">Book now</a>
                                {% else %}
                               
                            <a class="booknow-btn" href="{% url 'booking:booking_date'  barber.pk %}"
                                style="background-color: gray; pointer-events: none; cursor: default;">NOT AVAILABLE</a>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
         
           
         
        </div>
    </div>
</section>

core/templates/include/_footer.html
{% load static %}


<footer class="footer">

    <div class="footer-bottom">
        <div class="container-fluid">

            <div class="copyright">
                <div class="row">
                    <div class="col-md-6 col-lg-6">
                        <div class="copyright-text">
                            <p class="mb-0">&copy; 2022 Doccure. All rights reserved.</p>
                        </div>
                    </div>
                    <div class="col-md-6 col-lg-6">

                        <div class="copyright-menu">
                            <ul class="policy-menu">
                            <li><a href="https://github.com/liam1550" target="_blank">created by mohammad khalili</a></li>

                            </ul>
                        </div>

                    </div>
                </div>
            </div>

        </div>
    </div>

</footer>

core/templates/include/_header.html
{% load static %}



<header class="header">
    <nav class="navbar navbar-expand-lg header-nav">
        <div class="navbar-header">
            <a id="mobile_btn" href="javascript:void(0);">
                <span class="bar-icon">
                    <span></span>
                    <span></span>
                    <span></span>
                </span>
            </a>
            <a href="{% url 'pages:home' %}" class="navbar-brand logo">
                <img src="{% static 'img/logo/logo2.png' %}" class="img-fluid" alt="Logo">
            </a>
        </div>
        <div class="main-menu-wrapper">
            <div class="menu-header">
                <a href="{% url 'pages:home' %}" class="menu-logo">
                    <img src="{% static 'img/logo/logo2.jpg' %}" class="img-fluid" alt="Logo">
                </a>
                <a id="menu_close" class="menu-close" href="javascript:void(0);">
                    <i class="fas fa-times"></i>
                </a>
            </div>
            <ul class="main-nav">

                <li class="has-submenu">
                    <a href="#">Barbers <i class="fas fa-chevron-down"></i></a>
                    <ul class="submenu">
                        <li><a href="{% url 'pages:list_barber' %}">List of all Barbers</a></li>
                    </ul>
                </li>


                {% if request.user.role == 'ADMIN' %}
                <li>
                    <a href="{% url 'admin:index' %}" target="_blank">Admin</a>
                </li>
                {% endif %}
                <li class="login-link">
                    <a href="login.html">Login / Signup</a>
                </li>
            </ul>
        </div>


        {% if request.user.is_authenticated %}
        <ul class="nav header-navbar-rht">

            <li class="nav-item dropdown has-arrow logged-item">
                <a href="#" class="dropdown-toggle nav-link" data-bs-toggle="dropdown">
                    <span class="user-img">
                        <img class="rounded-circle" src="{% static 'img/patients/patient2.jpg' %}" width="31"
                            alt="{{ request.user }}">
                    </span>
                </a>
                <div class="dropdown-menu dropdown-menu-end">
                    <div class="user-header">
                        <div class="avatar avatar-sm">
                            <img src="{% static 'img/patients/patient2.jpg' %}" alt="User Image"
                                class="avatar-img rounded-circle">
                        </div>
                        <div class="user-text">
                            <h6></h6>{{ request.user.last_name }}</h6>
                            <p class="text-muted mb-0">{{ request.user.role }}</p>
                        </div>
                    </div>
                    {% if request.user.role == 'CUSTOMERUSER' %}
                    <a class="dropdown-item"
                        href="{% url 'customers:customer_panel' %}">Dashboard</a>
                    <a class="dropdown-item" href="{% url 'customers:edit_profile' %}">Profile Settings</a>
                    {% elif request.user.role == 'ADMIN' %}
                    <a class="dropdown-item" href="{% url 'admin:index' %}" target="_blank">Admin</a>

                    {% endif %}

                    <a class="dropdown-item" href="{% url 'accounts:user_logout' %}">Logout</a>
                </div>
            </li>

        </ul>
        {% else %}
        <ul class="nav header-navbar-rht">
            <li class="nav-item">
                <a class="nav-link header-login" href="{% url 'accounts:user_login' %}">login / Signup </a>
            </li>
        </ul>

        {% endif %}
    </nav>
</header>

core/templates/include/_scripts.html
   {% load static %}
   <script src="{% static 'js/jquery-3.6.0.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/moment.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/script.js' %}" type="text/javascript"></script>
    <script src="{% static 'cdn-cgi/scripts/7d0fa10a/cloudflare-static/rocket-loader.min.js' %}" data-cf-settings="|49"
        defer=""></script>

core/templates/include/_sidebar.html
<div class="profile-sidebar">
    <div class="widget-profile pro-widget-content">
        <div class="profile-info-widget">
            <a href="#" class="booking-doc-img">
                <img src="{{ barber.image.url }}" alt="User Image">
            </a>
            <div class="profile-det-info">
                <h3>{{ barber }}</h3>
                <div class="patient-details">
                    <h5 class="mb-0">BDS, MDS - Oral & Maxillofacial Surgery</h5>
                </div>
            </div>
        </div>
    </div>
    <div class="dashboard-widget">
        <nav class="dashboard-menu">
            <ul>
                <li class="active">
                    <a href="{% url 'barbers:barber_panel' barber_id=barber.pk %}">
                        <i class="fas fa-columns"></i>
                        <span>Dashboard</span>
                    </a>
                </li>
                <li>
                    <a href="#">
                        <i class="fas fa-calendar-check"></i>
                        <span>Appointments</span>
                    </a>
                </li>
                <li>
                    <a href="#">
                        <i class="fas fa-user-injured"></i>
                        <span>My Patients</span>
                    </a>
                </li>
                <li>
                    <a href="{% url 'barbers:barber_schedule' barber_id=barber.pk %}">
                                    <i class="fas fa-hourglass-start"></i>
                                    <span>Schedule Timings</span>
                        <!-- Your link content here -->
                    </a>
          
                    
                </li>
                <li>
                    <a href="#">
                        <i class="fas fa-file-invoice"></i>
                        <span>Invoices</span>
                    </a>
                </li>
                <li>
                    <a href="#">
                        <i class="fas fa-star"></i>
                        <span>Reviews</span>
                    </a>
                </li>

                <li>
                    <a href="#">
                        <i class="fas fa-user-cog"></i>
                        <span>Profile Settings</span>
                    </a>
                </li>
                <li>
                    <a href="#">
                        <i class="fas fa-share-alt"></i>
                        <span>Social Media</span>
                    </a>
                </li>
                <li>
                    <a href="#">
                        <i class="fas fa-lock"></i>
                        <span>Change Password</span>
                    </a>
                </li>
                <li>
                    <a href="#">
                        <i class="fas fa-sign-out-alt"></i>
                        <span>Logout</span>
                    </a>
                </li>
            </ul>
        </nav>
    </div>
</div>

core/templates/include/cus_panel_sidebar.html
<div class="col-md-5 col-lg-4 col-xl-3 theiaStickySidebar">
    <div class="profile-sidebar">
        <div class="widget-profile pro-widget-content">
            <div class="profile-info-widget">
          
                <div class="profile-det-info">
                    <h3>{{ customer }}</h3>
                    <div class="patient-details">
                        <h5><i class="fas fa-birthday-cake"></i> 24 Jul 1983, 38 years</h5>
                    </div>
                </div>
            </div>
        </div>
        <div class="dashboard-widget">
            <nav class="dashboard-menu">
                <ul>
                    <li class="active">
                        <a href="{% url 'customers:customer_panel' %}">
                            <i class="fas fa-columns"></i>
                            <span>Dashboard</span>
                        </a>
                    </li>
      

                    <li>
                        <a href="{% url 'customers:edit_profile' %}">
                            <i class="fas fa-user-cog"></i>
                            <span>Profile Settings</span>
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'accounts:change_password' %}">
                            <i class="fas fa-lock"></i>
                            <span>Change Password</span>
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'accounts:user_logout' %}">
                            <i class="fas fa-sign-out-alt"></i>
                            <span>Logout</span>
                        </a>
                    </li>
                </ul>
            </nav>
        </div>
    </div>
</div>

core/templates/include/messages.html
{% if messages %}
    {% for msg in messages %}
    <div class="alert alert-{{ msg.tags }} alert-dismissible fade show" role="alert">
        <li>{{ msg }}</li>

            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    {% endfor %}
{% endif %}

<!-- {% if messages %}
{% for msg in messages %}
<p class="alert alert-{{ msg.tags }}">{{ msg }}</p>
{% endfor %}
{% endif %} -->